config/routes.rb
API_SUBDOMAIN = { subdomain: /\A(staging-)?api\Z/ }.freeze unless defined? API_SUBDOMAIN

BuckyBox::Application.routes.draw do
  apipie

  devise_for :admins,       controllers: { sessions: "admin/sessions" }
  devise_for :distributors, controllers: { sessions: "distributor/sessions", passwords: "distributor/passwords" }
  devise_for :customers,    controllers: { sessions: "customer/sessions", passwords: "customer/passwords" }

  get "/ping" => "application#ping"
  get "/delayed_job" => DelayedJobWeb, anchor: false
  get "/" => "api#index", constraints: API_SUBDOMAIN

  root to: "distributor/customers#index"

  namespace :sign_up_wizard do
    get "form"
    get "country"
    post "sign_up"
  end

  namespace :distributor do
    root to: "welcome#index"

    namespace :settings do
      get "organisation"
      get "webstore"
      post "webstore", action: "save_webstore"
      post "spend_limit_confirmation"

      resource :delivery_services, only: [:show, :create, :update, :destroy]

      namespace :products do
        resource :boxes, only: [:show, :create, :update]
        resource :box_items, only: [:show, :create, :update]
        resource :extra_items, only: [:show, :create, :update]
      end

      namespace :payments do
        resource :bank_deposit, controller: "bank_deposit", only: [:show, :update]
        resource :cash_on_delivery, controller: "cash_on_delivery", only: [:show, :update]
        resource :paypal, controller: "paypal", only: [:show, :update]
      end
    end

    namespace :notifications do
      post "dismiss_all", actions: "dismiss_all", as: "dismiss_all"
    end

    namespace :intro_tour do
      post "dismiss", actions: "dismiss", as: "dismiss"
    end

    namespace :reports do
      get "/",                               action: "index"
      get "transaction_history/:start/:to",  action: "transaction_history",      as: "transaction_history"
      get "customer_account_history/:to",    action: :customer_account_history,  as: "customer_account_history"
    end

    resource :billing, only: :show, controller: "billing"
    resource :pricing, only: :update, controller: "pricing"

    resources :distributors,        only: :update
    resource  :bank_information,    only: :update
    resources :boxes,               except: [:index]
    resources :extras,              except: [:index, :show]

    resources :line_items, except: [:index, :show, :update] do
      collection do
        put "bulk_update", action: :bulk_update, as: "bulk_update"
      end
    end

    resources :deliveries

    resources :payments, only: [:index, :destroy] do
      collection do
        post "match_payments", action: "match_payments", as: "match_payments"
      end

      member do
        put "process_payments", action: "process_payments", as: "process_payments"
      end
    end

    resources :import_transactions, only: [:update] do
      member do
        get "load_more_rows/:position", action: "load_more_rows", as: "load_more_rows"
      end
    end

    resources :import_transaction_lists, only: [:destroy]

    resources :customers, except: [:edit] do
      collection do
        get "search",   action: :index, as: "search"
        get "tag/:tag", action: :index, as: "tag"
        post "email"
        post "export"
      end

      member do
        get :send_login_details
        get "impersonate"
        get "activity"
        get "edit_profile",             action: "edit_profile",             as: "edit_profile"
        put "update_profile",           action: "update_profile",           as: "update_profile"
        get "edit_delivery_details",    action: "edit_delivery_details",    as: "edit_delivery_details"
        put "update_delivery_details",  action: "update_delivery_details",  as: "update_delivery_details"
      end
    end

    resources :accounts, only: :edit do
      resources :orders, except: [:index, :show, :destroy] do
        member do
          put "deactivate"
          put "pause"
          post "remove_pause"
          put "resume"
          post "remove_resume"
        end
      end

      resources :boxes do
        member do
          get "extras"
        end
      end

      member do
        put "change_balance", action: :change_balance, as: "change_balance"
        get "transactions/:limit(/:more)", action: :transactions, as: "transactions"
        get "receive_payment", action: :receive_payment, as: "receive_payment"
        post "save_payment",   action: :save_payment, as: "save_payment"
      end
    end
  end

  namespace :customer do
    root to: "dashboard#index"

    get "dashboard",               controller: "dashboard", action: "index"
    get "order/:order_id/box/:id", controller: "dashboard", action: "box"

    put "update_contact_details",   controller: "customers",  action: "update_contact_details"
    put "update_delivery_address",  controller: "customers",  action: "update_delivery_address"
    put "update_password",          controller: "customers",  action: "update_password"

    resources :boxes, only: [:show] do
      member do
        get "extras"
      end
    end

    resources :orders, only: [:edit, :update] do
      member do
        put "pause"
        post "remove_pause"
        put "resume"
        post "remove_resume"
        put "deactivate"
      end
    end

    resources :accounts, only: [] do
      get "transactions/:limit(/:more)", action: :transactions, as: "transactions"
    end
  end

  namespace :admin do
    root to: "dashboard#index"

    resources :cron_logs, only: :index
    resources :style_sheet, only: :index

    resources :metrics, only: [:index] do
      collection do
        get "transactional_customers"
        get "sales"
      end
    end

    resources :distributors, only: [:index, :new, :create, :edit, :update] do
      member do
        get "impersonate"
      end

      collection do
        get "unimpersonate"
        get "country_setting/:id", controller: "distributors", action: "country_setting"
        get "tag/:tag", action: :index, as: "tag"
      end
    end

    resources :omni_importers do
      member do
        post "test"
      end
    end
  end

  namespace :api, path: "", defaults: { format: :json }, constraints: API_SUBDOMAIN do
    namespace :v1 do
      get  "ping"                => "base#ping"
      post "csp-report"          => "base#csp_report"
      get  "geoip(/:ip)"         => "base#geoip", constraints: { ip: %r{[^\/]+} } # accept IP including dots

      post "/customers/sign_in"
      resources :customers,         only: [:index, :show, :create, :update]
      resources :boxes,             only: [:index, :show]
      resources :delivery_services, only: [:index, :show]
      resources :orders,            only: [:index, :show, :create]
      resources :webstores,         only: [:index] # all webstores
      resource  :webstore,          only: [:show] # current webstore
      resources :deliveries,        only: [:index] do
        get :pending, on: :collection
      end
    end
  end

  # TODO: Legacy routes. As we move to all RESTful routes these should be removed.
  get "/distributor/deliveries/date/:date/view/:view",            controller: "distributor/deliveries", action: :index,                           as: "date_distributor_deliveries"
  post "/distributor/deliveries/date/:date/reposition",           controller: "distributor/deliveries", action: :reposition,                      as: "reposition_distributor_deliveries"
  post "/distributor/deliveries/update_status",                   controller: "distributor/deliveries", action: :update_status,                   as: "update_status_distributor_deliveries"
  post "/distributor/deliveries/make_payment",                    controller: "distributor/deliveries", action: :make_payment,                    as: "make_payment_distributor_deliveries"
  post "/distributor/deliveries/master_packing_sheet",            controller: "distributor/deliveries", action: :master_packing_sheet,            as: "master_packing_sheet_distributor_deliveries"

  post "/distributor/deliveries/export",                          controller: "distributor/export/deliveries",               action: :index, as: "export_distributor_deliveries"
  post "/distributor/deliveries/export_extras",                   controller: "distributor/export/extras",                   action: :index, as: "export_extras_distributor_deliveries"
  post "/distributor/deliveries/export_exclusions_substitutions", controller: "distributor/export/exclusions_substitutions", action: :index, as: "export_exclusions_substitutions_distributor_deliveries"
end

app/models/distributor/defaults.rb
class Distributor::Defaults
  def self.populate_defaults(distributor)
    defaults = new(distributor)
    defaults.populate_defaults
  end

  def initialize(distributor)
    @distributor = distributor
  end

  def populate_defaults
    populate_pricing
    populate_line_items
    populate_bank_information
    populate_paypal_information
    populate_email_templates
    distributor.save
  end

private

  attr_accessor :distributor

  def populate_pricing
    pricing = Distributor::Pricing.default_pricing_for_currency(distributor.currency)
    pricing.distributor = distributor
    pricing.save!
  end

  def populate_line_items
    LineItem.add_defaults_to(distributor)
  end

  def populate_bank_information
    bank_information = distributor.bank_information || distributor.create_bank_information

    banks = distributor.omni_importers.bank_deposit
    bank_information.name = banks.first.bank_name unless banks.empty?
    bank_information.account_name = distributor.name
    bank_information.cod_payment_message = "Please place payment in your mailbox."

    bank_information.save(validate: false) # because model is missing account number
  end

  def populate_paypal_information
    distributor.paypal_email = distributor.email
  end

  def populate_email_templates
    distributor.email_templates = email_templates
  end

  def email_templates
    templates.map { |template| EmailTemplate.new(template[:subject], template[:body]) }
  end

  def templates
    [
      account_overdue_email,
      login_for_ordering_email,
      weekly_newsleter_email,
    ]
  end

  def customer_login_url
    url_helper.new_customer_session_url(host: app_host, distributor: distributor_parameter_name)
  end

  def customer_reset_password_url
    url_helper.new_customer_password_url(host: app_host, distributor: distributor_parameter_name)
  end

  def distributor_name
    distributor.name
  end

  def distributor_parameter_name
    distributor.parameter_name
  end

  def app_host
    Figaro.env.host
  end

  def url_helper
    Rails.application.routes.url_helpers
  end

  # TODO: Figure out the best way to move the email content below into a config file

  def account_overdue_email
    {
      subject: "Your account is overdue",
      body: <<-BODY
Hi {first_name},

Just a reminder that your account balance is overdue.

Your existing balance is: {account_balance}

You can login to your account to check your account history and make payments here:
#{customer_login_url}

Cheers
-The team at #{distributor_name}
      BODY
    }
  end

  def login_for_ordering_email
    {
      subject: "Accessing your account on our new online ordering system",
      body: <<-BODY
Hi {first_name},

We've migrated onto a new online ordering system called Bucky Box.

In order to access your account on Bucky Box please follow the steps below to set up your password.

1) Click this link: #{customer_reset_password_url}

2) Enter your email address we have on record: {email_address}

3) An email message will be sent to you with a "Change my password" link. Clicking this will let you assign yourself a password and you'll be able to access your dashboard immediately.

You can log into your account at anytime to:
- Check your transaction history
- Make or change orders
- Pause your deliveries
- Update your delivery address

Cheers
-The team at #{distributor_name}
      BODY
    }
  end

  def weekly_newsleter_email
    {
      subject: "Weekly Newsletter - What's in your box this week",
      body: <<-BODY
Hi {first_name},

Thanks for supporting.

WHAT'S IN YOUR BOX THIS WEEK

As you know, we source the best seasonal produce from around the region, so here's some of the delicious fresh items you might find in your box this week;
- INSERT PRODUCE LIST HERE

TOP RECIPE TIPS

Here's our top 3 recipes which include some of the ingredients you have to cook with:
- ADD RECIPE LINKS HERE

BITE SIZE KNOWLEDGE

A key part of what drives us is creating a thriving, diverse food system - it's better for people and planet.

As part of that vision we scour the markets, farms and seedbanks for interesting produce which we add to your delivery.

This week's lesser-known food stuff is INSERT FOOD ITEM HERE, AND A LITTLE INFORMATION ABOUT IT.

FEEDBACK

We love to hear your thoughts, good or bad, about how your experience with us is going. We strive to give you the best food delivery service around, so your insights are vital to us improving.

Drop us an email, tweet (@twitterhandle) or call anytime and we'll get back to you.

Thank you for your loyal custom and for supporting a better food system.

OWNER/CUSTOMER SERVICE NAME
#{distributor_name}
CONTACT DETAILS
      BODY
    }
  end
end

app/models/distributor/form/edit_customer_delivery_details.rb
require_relative "edit_customer_delivery_details_fields"

class Distributor::Form::EditCustomerDeliveryDetails
  include Distributor::Form::EditCustomerDeliveryDetailsFields

protected

  def customer_args
    delivery_details_customer_args
  end

  def address_args
    delivery_details_address_args
  end
end

app/controllers/admin/distributors_controller.rb
class Admin::DistributorsController < Admin::ResourceController
  before_action :parameterize_name, only: [:create, :update]

  def index
    recent_delay = 6.months.ago
    @distributors = Distributor.where(
      "last_seen_at > ? OR created_at > ?", recent_delay, recent_delay
    ).order("last_seen_at DESC, created_at DESC")
    @distributors = @distributors.tagged_with(params[:tag]) if params[:tag].present?
    @hidden_distributors = Distributor.count - @distributors.count
    index!
  end

  def create
    create! do |success, _failure|
      success.html do
        Distributor::Defaults.populate_defaults(@distributor)
        redirect_to admin_root_url
      end
    end
  end

  def update
    update! do |success, _failure|
      success.html do
        redirect_to admin_root_url
      end
    end
  end

  def impersonate
    distributor = Distributor.find(params[:id])
    sign_in(distributor, bypass: true) # bypass means it won't update last logged in stats

    redirect_to distributor_root_url
  end

  def unimpersonate
    sign_out(:distributor)

    redirect_to admin_root_url
  end

  def country_setting
    @country = Country.find(params[:id])

    time_zone = ActiveSupport::TimeZone::MAPPING.find do |_, city|
      city == @country.time_zone
    end
    time_zone = time_zone.first if time_zone

    render json: {
      time_zone: time_zone,
      currency: @country.currency,
      fee: @country.default_consumer_fee_cents / 100.0,
    }
  end

private

  def parameterize_name
    if params[:distributor]
      parameterized_name = Distributor.parameterize_name(params[:distributor][:parameter_name])
      params[:distributor][:parameter_name] = parameterized_name
    end
  end
end

app/controllers/api/v1/deliveries_controller.rb
class Api::V1::DeliveriesController < Api::V1::BaseController
  def index
    date = params.fetch(:date)
    if Date.iso8601(date) > @distributor.window_end_at
      render json: nil, status: :unprocessable_entity and return
    end

    export = Distributor::Export::Utils.get_export(@distributor, params)
    csv_string = export.csv.first
    csv_array = CSV.parse(csv_string)

    render json: csv_array
  end

  def pending
    render json: {
      window_start_from: @distributor.window_start_from,
      window_end_at: @distributor.window_end_at,
    }
  end
end

app/controllers/distributor/accounts_controller.rb
class Distributor::AccountsController < Distributor::ResourceController
  respond_to :html, :json

  def change_balance
    @account = Account.find(params[:id])

    respond_to do |format|
      if create_transaction(@account, params)
        format.html { redirect_to [:distributor, @account.customer], notice: 'Account balance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to [:distributor, @account.customer] }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def transactions
    offset_size = 0
    limit = params[:limit].to_i
    limit ||= 6

    limit += 100 if params[:more].present?
    @account = current_distributor.accounts.find(params[:id])
    @transactions = account_transactions(@account, offset_size, limit)
    @show_more_link = @transactions.size != @account.transactions.count

    @transactions_sum = @account.calculate_balance(offset_size)

    render partial: 'distributor/transactions/index'
  end

private

  def create_transaction(account, params)
    opts = {}
    delta = CrazyMoney.new(params[:delta])

    if delta.zero?
      flash[:error] = 'Change in balance must be a number and not zero.'
    else
      opts[:delta] = delta
    end

    opts[:description] = params[:note] if params[:note].present?

    if params[:date].present?
      opts[:display_time] = Date.parse(params[:date]).to_time_in_current_zone
    end

    !delta.zero? && account.create_transaction(delta, opts)
  end
end

app/views/distributor/deliveries/_controls.html.haml
.row-fluid.data-headings
  .span12.action-buttons
    .btn-group
      = button_tag class: 'btn btn-primary' do
        = check_box_tag 'select_all'

      = button_tag class: "btn btn-primary dropdown-toggle", data: { toggle: 'dropdown' } do
        %span.caret
      %ul.dropdown-menu{ role: 'menu' }
        %li
          = link_to 'javascript:void(0)', id: 'select_all-all' do
            All
        %li
          = link_to 'javascript:void(0)', id: 'select_all-none' do
            None
        %li
          = link_to 'javascript:void(0)', id: 'select_all-inverse' do
            Inverse

    - if @real_list && params[:view] != 'packing'
      .btn-group.conditional-actions
        = button_tag class: 'btn btn-primary', id: 'delivered' do
          %i.icon-ok-sign.icon-white
          Mark As Delivered

        = button_tag class: "btn btn-primary dropdown-toggle", data: { toggle: 'dropdown' } do
          %span.caret
        %ul#missed-options.dropdown-menu{ role: 'menu' }
          %li
            = link_to '#', id: 'pending', tabindex: -1 do
              %i.icon-time
              Mark delivery as pending
          %li
            = link_to '#', id: 'cancelled', tabindex: -1 do
              %i.icon-remove-sign
              Mark delivery as cancelled
          %li.divider
          %li= link_to 'Apply cash on delivery', '#', id: 'payment-on-delivery', tabindex: -1
          %li= link_to 'Cancel cash on delivery', '#', id: 'undo-payment', tabindex: -1

    .btn-group.conditional-actions
      = link_to "javascript:void(0)", class: "btn btn-primary export-details", role: "button" do
        %i.icon-share.icon-white
        - if params[:view] == 'packing'
          Export Packing Details
        - else
          Export Delivery Details

      = button_tag class: "btn btn-primary dropdown-toggle", data: { toggle: 'dropdown' } do
        %span.caret
      %ul.dropdown-menu{ role: 'menu' }
        - if params[:view] == 'packing'
          - if @real_list
            %li
              = link_to "Print packing summary", "javascript:void(0)", id: 'master-print'
            - if current_distributor.addons.include?(:labels)
              %li
                = link_to "Print labels", "https://addons.buckybox.com/labels?key=#{current_distributor.api_key}&secret=#{current_distributor.api_secret}&date=#{@selected_date}", target: "_blank", method: :post
            - if current_distributor.addons.include?(:delivery)
              %li
                = link_to "Print delivery summaries", "https://addons.buckybox.com/delivery?key=#{current_distributor.api_key}&secret=#{current_distributor.api_secret}&date=#{@selected_date}", target: "_blank", method: :post
            - if current_distributor.addons.include?(:packing)
              %li
                = link_to "Print packing sheets", "https://addons.buckybox.com/packing?key=#{current_distributor.api_key}&secret=#{current_distributor.api_secret}&date=#{@selected_date}", target: "_blank", method: :post
            %li.divider

          -# %li
          -#   = link_to "Export extras summary", "javascript:void(0)" # NOTE: eventually move it here
          %li
            = link_to "Export excludes and substitutes summary", "javascript:void(0)", id: 'export-exclusions-substitutions'
          %li.divider

        %li
          = link_to "Send email", "#distributor_send_email", "data-toggle" => "modal"
        %li
          = link_to "#distributor_copy_email", "data-toggle" => "modal" do
            View as email addresses

    %form{action: master_packing_sheet_distributor_deliveries_path, method: 'post', target: '_blank', id: 'master-print-form'}
      = token_tag(nil)

    %form{action: export_distributor_deliveries_path, method: 'post', id: 'export-details-form'}
      = token_tag(nil)

    %form{action: export_exclusions_substitutions_distributor_deliveries_path, method: 'post', id: 'export-exclusions-substitutions-form'}
      = token_tag(nil)

= render partial: "distributor/shared/email_templates"

app/views/distributor/deliveries/_date_navigation.html.haml
- unless @date_navigation.empty?
  .row-fluid
    #calendar-navigation.span12
      %ul{ style: calendar_nav_length(@date_navigation, @months) }
        - @months.each do |month, dates|
          %li.month= Date::ABBR_MONTHNAMES[month].upcase

          - dates.each do |date|
            %li{ id: count_selected(@date_navigation.first, date, params[:date]) }
              = cache_if(date < current_distributor.window_end_at - Distributor::MAX_ADVANCED_DAYS, [:date_navigation, current_distributor.id, date]) do
                = link_to date_distributor_deliveries_path(date, params[:view]), title: date_title(current_distributor, date) do
                  .date= date.strftime("%d %a").upcase
                  .count{ class: date_class(current_distributor, date) }= delivery_quantity(current_distributor, date)

app/views/distributor/deliveries/_day_details.html.haml
- if @selected_date
  #delivery-listings.row-fluid{ data: { distributor: current_distributor.id, date: @selected_date } }
    #side-navigation.span3
      %fieldset
        %legend packing
        .tabbable.tabs-left
          %ul.nav.nav-tabs
            %li{ class: "#{'active' if @delivery_service_id == 0}" }
              = link_to date_distributor_deliveries_path(@selected_date, 'packing') do
                All Boxes
                %span.badge= @all_items.count

      %fieldset
        %legend deliveries
        .tabbable.tabs-left
          %ul.nav.nav-tabs
            - @delivery_services.each do |delivery_service|
              %li{ class: "#{'active' if @delivery_service_id == delivery_service.id}" }
                = link_to date_distributor_deliveries_path(@selected_date, delivery_service.id) do
                  = delivery_service.name
                  %span.badge= @all_item_counts_by_delivery_service_id[delivery_service.id] || 0

      - if params[:view] == 'packing' && !@items.blank?
        %fieldset
          %legend summary
          - boxes = DeliverySort.new(@items).grouped_by_boxes
          - extras = @items.collect(&:extras_summary).flatten

          - unless boxes.blank?
            %dl.packing-summary
              %dt Boxes
              - boxes.each do |box, array|
                %dd
                  %span.badge= array.map(&:quantity).sum
                  = box.name

          - unless extras.blank?
            %dl.packing-summary
              %dt Extras
              - extras.sort{|a,b| Extra.name_with_unit(a).downcase<=>Extra.name_with_unit(b).downcase}.group_by{ |g| "#{g[:name]} #{g[:unit]}" }.each do |extra, array|
                %dd
                  %span.badge= array.collect{ |a| a[:count].to_i }.sum
                  = "#{extra}"
              %dd
                .minor-action= link_to "export extras summary", "javascript:void(0)", id: "link_to_download_extras_csv"
                = simple_form_for(:export_extras, url: export_extras_distributor_deliveries_path, html:{style:'display:none', id: 'export_extras_form'}) do |f|
                  = f.input :date, as: :hidden, input_html: {value: @selected_date.to_s(:db)}

    #delivery-list.span9
      - if @items.blank?
        %h3 No Deliveries
        %p
          There are no deliveries for
          %strong= @delivery_service.name
          on
          %strong= @selected_date.strftime("%A %d %B")
      - else
        = render 'controls'

        - if @delivery_service_id != 0
          = render 'delivery_service_list'
        - else
          = render 'packing_list'

app/views/distributor/deliveries/_delivery_service_list.html.haml
.row-fluid.data-headings

- if @real_list
  #list_type{ data: { type: 'deliveries', date: @selected_date, screen: 'delivery' } }
    %ul#delivery_list.unstyled{ class: (@delivery_list.date.past? ? '' : 'sortable') }
      - DeliverySort.new(@items).grouped_by_addresses.each_value do |deliveries|
        %li.row-fluid
          .span12
            %ul.unstyled
              - deliveries.each do |delivery|
                %li.row-fluid.data-listings.customer-row.row-grip{ class: delivery.status, data: { delivery_id: delivery.id } }
                  .span6.customer
                    = check_box_tag delivery.order_id, '1', false, data: { deliveries: delivery.id }, class: 'select_one', 'data-customer-id' => delivery.customer.id
                    .label.state-label.dso-number
                      = map_pin(delivery)
                      = link_to delivery.formated_delivery_number, '#', title: "Delivery Sequence Number (printed on labels)"
                    = render partial: 'status_icons', locals: { status: delivery.status }
                    .customer-holder
                      = customer_badge(delivery.customer, customer_name: delivery.package.archived_customer_name)
                    = customer_tags(delivery.customer)

                  .span1{class: "paid-label #{'paid' if delivery.paid?}"}
                    &nbsp;

                  .span5
                    .row-fluid.address-description
                      .span6= display_address(delivery)
                      .span6.box-description= contents_description(delivery, @selected_date)

- else
  #list_type{ data: { type: 'orders', date: @selected_date, screen: 'delivery' } }
    %ul#delivery_list.unstyled
      - @items.each do |order|
        %li.row-fluid.data-listings.pending.customer-row
          .span6.customer
            = check_box_tag order.id, '1', false, data: { orders: order.id }, class: 'select_one', 'data-customer-id' => order.customer.id
            .label.state-label.dso-number= map_pin(order)
            .label.state-label.staus-icon.status-pending{ title: 'PENDING delivery' }
              %i.icon-time
            .customer-holder= customer_badge(order.customer)
            = customer_tags(order.customer)

          .span6
            .row-fluid.address-description
              .span6= display_address(order)
              .span6= contents_description(order, @selected_date)

app/views/distributor/deliveries/_packing_list.html.haml
- if @real_list
  - DeliverySort.new(@items).grouped_by_boxes.each do |box, array|
    .row-fluid.data-headings
      .span12
        %strong= box.name

    #list_type{ data: { type: 'packages', date: @selected_date, screen: 'packing' } }
      %ul#delivery_list.unstyled
        - array.each do |package|
          %li.row-fluid.data-listings.customer-row{ class: package.status }
            .span6.customer
              = check_box_tag package.order_id, '1', false, data: { packages: package.id }, class: 'select_one', 'data-customer-id' => package.customer.id
              .label.state-label.dso-number= map_pin(package)
              = render partial: 'status_icons', locals: { status: package.status }
              .customer-holder
                = customer_badge(package.customer, customer_name: package.archived_customer_name, short: true)
              = customer_tags(package.customer)

            .span6
              .row-fluid.address-description
                .span6= display_address(package)
                .span6= contents_description(package, @selected_date)
- else
  - DeliverySort.new(@items).grouped_by_boxes.each do |box, array|
    .row-fluid.data-headings
      .span12
        %strong= box.name

    #list_type{ data: { type: 'orders', date: @selected_date, screen: 'packing' } }
      %ul#delivery_list.unstyled
        - array.each do |order|
          %li.row-fluid.data-listings.pending.customer-row
            .span6.customer
              = check_box_tag order.id, '1', false, data: { orders: order.id }, class: 'select_one', 'data-customer-id' => order.customer.id
              .label.state-label.dso-number= map_pin(order)
              .label.state-label.staus-icon.status-unpacked{ title: 'UNPACKED package' }
                %i.icon-time
              .customer-holder= customer_badge(order.account.customer)
              = customer_tags(order.customer)

            .span6
              .row-fluid.address-description
                .span6= display_address(order)
                .span6= contents_description(order, @selected_date)

app/views/distributor/deliveries/_status_icons.html.haml
-# Still gross but not the time to fix. Should be easier to do with just JS now though.

.label.state-label.staus-icon{ style: icon_display(status, 'unpacked'), class: 'status-unpacked', title: 'UNPACKED package' }
  %i.icon-time
.label.state-label.staus-icon{ style: icon_display(status, 'packed'), class: 'status-packed', title: 'Package has been PACKED' }
  %i.icon-ok-sign

.label.state-label.staus-icon{ style: icon_display(status, 'pending'), class: 'status-pending', title: 'PENDING delivery' }
  %i.icon-time
.label.state-label.staus-icon{ style: icon_display(status, 'delivered'), class: 'status-delivered', title: 'Delivery has been COMPLETED' }
  %i.icon-ok-sign
.label.state-label.staus-icon{ style: icon_display(status, 'cancelled'), class: 'status-cancelled', title: 'MISSED DELIVERY, customer has not been charged' }
  %i.icon-remove-sign
.label.state-label.staus-icon{ style: icon_display(status, 'rescheduled'), class: 'status-rescheduled', title: 'Missed delivery, REDELIVERED' }
  %i.icon-remove-sign
.label.state-label.staus-icon{ style: icon_display(status, 'repacked'), class: 'status-repacked', title: 'Missed delivery, NEW BOX scheduled' }
  %i.icon-remove-sign

app/views/distributor/deliveries/index.html.haml
- title 'Deliveries', false
= intro_tour(@show_tour)

= render 'date_navigation'
= render 'day_details'