config/routes.rb
API_SUBDOMAIN = { subdomain: /\A(staging-)?api\Z/ }.freeze unless defined? API_SUBDOMAIN

BuckyBox::Application.routes.draw do
  apipie

  devise_for :admins,       controllers: { sessions: "admin/sessions" }
  devise_for :distributors, controllers: { sessions: "distributor/sessions", passwords: "distributor/passwords" }
  devise_for :customers,    controllers: { sessions: "customer/sessions", passwords: "customer/passwords" }

  get "/ping" => "application#ping"
  get "/delayed_job" => DelayedJobWeb, anchor: false
  get "/" => "api#index", constraints: API_SUBDOMAIN

  root to: "distributor/customers#index"

  namespace :sign_up_wizard do
    get "form"
    get "country"
    post "sign_up"
  end

  namespace :distributor do
    root to: "welcome#index"

    namespace :settings do
      get "organisation"
      get "webstore"
      post "webstore", action: "save_webstore"
      post "spend_limit_confirmation"

      resource :delivery_services, only: [:show, :create, :update, :destroy]

      namespace :products do
        resource :boxes, only: [:show, :create, :update]
        resource :box_items, only: [:show, :create, :update]
        resource :extra_items, only: [:show, :create, :update]
      end

      namespace :payments do
        resource :bank_deposit, controller: "bank_deposit", only: [:show, :update]
        resource :cash_on_delivery, controller: "cash_on_delivery", only: [:show, :update]
        resource :paypal, controller: "paypal", only: [:show, :update]
      end
    end

    namespace :notifications do
      post "dismiss_all", actions: "dismiss_all", as: "dismiss_all"
    end

    namespace :intro_tour do
      post "dismiss", actions: "dismiss", as: "dismiss"
    end

    namespace :reports do
      get "/",                               action: "index"
      get "transaction_history/:start/:to",  action: "transaction_history",      as: "transaction_history"
      get "customer_account_history/:to",    action: :customer_account_history,  as: "customer_account_history"
    end

    resource :billing, only: :show, controller: "billing"
    resource :pricing, only: :update, controller: "pricing"

    resources :distributors,        only: :update
    resource  :bank_information,    only: :update
    resources :boxes,               except: [:index]
    resources :extras,              except: [:index, :show]

    resources :line_items, except: [:index, :show, :update] do
      collection do
        put "bulk_update", action: :bulk_update, as: "bulk_update"
      end
    end

    resources :deliveries

    resources :payments, only: [:index, :destroy] do
      collection do
        post "match_payments", action: "match_payments", as: "match_payments"
      end

      member do
        put "process_payments", action: "process_payments", as: "process_payments"
      end
    end

    resources :import_transactions, only: [:update] do
      member do
        get "load_more_rows/:position", action: "load_more_rows", as: "load_more_rows"
      end
    end

    resources :import_transaction_lists, only: [:destroy]

    resources :customers, except: [:edit] do
      collection do
        get "search",   action: :index, as: "search"
        get "tag/:tag", action: :index, as: "tag"
        post "email"
        post "export"
      end

      member do
        get :send_login_details
        get "impersonate"
        get "activity"
        get "edit_profile",             action: "edit_profile",             as: "edit_profile"
        put "update_profile",           action: "update_profile",           as: "update_profile"
        get "edit_delivery_details",    action: "edit_delivery_details",    as: "edit_delivery_details"
        put "update_delivery_details",  action: "update_delivery_details",  as: "update_delivery_details"
      end
    end

    resources :accounts, only: :edit do
      resources :orders, except: [:index, :show, :destroy] do
        member do
          put "deactivate"
          put "pause"
          post "remove_pause"
          put "resume"
          post "remove_resume"
        end
      end

      resources :boxes do
        member do
          get "extras"
        end
      end

      member do
        put "change_balance", action: :change_balance, as: "change_balance"
        get "transactions/:limit(/:more)", action: :transactions, as: "transactions"
        get "receive_payment", action: :receive_payment, as: "receive_payment"
        post "save_payment",   action: :save_payment, as: "save_payment"
      end
    end
  end

  namespace :customer do
    root to: "dashboard#index"

    get "dashboard",               controller: "dashboard", action: "index"
    get "order/:order_id/box/:id", controller: "dashboard", action: "box"

    put "update_contact_details",   controller: "customers",  action: "update_contact_details"
    put "update_delivery_address",  controller: "customers",  action: "update_delivery_address"
    put "update_password",          controller: "customers",  action: "update_password"

    resources :boxes, only: [:show] do
      member do
        get "extras"
      end
    end

    resources :orders, only: [:edit, :update] do
      member do
        put "pause"
        post "remove_pause"
        put "resume"
        post "remove_resume"
        put "deactivate"
      end
    end

    resources :accounts, only: [] do
      get "transactions/:limit(/:more)", action: :transactions, as: "transactions"
    end
  end

  namespace :admin do
    root to: "dashboard#index"

    resources :cron_logs, only: :index
    resources :style_sheet, only: :index

    resources :metrics, only: [:index] do
      collection do
        get "transactional_customers"
        get "sales"
      end
    end

    resources :distributors, only: [:index, :new, :create, :edit, :update] do
      member do
        get "impersonate"
      end

      collection do
        get "unimpersonate"
        get "country_setting/:id", controller: "distributors", action: "country_setting"
        get "tag/:tag", action: :index, as: "tag"
      end
    end

    resources :omni_importers do
      member do
        post "test"
      end
    end
  end

  namespace :api, path: "", defaults: { format: :json }, constraints: API_SUBDOMAIN do
    namespace :v1 do
      get  "ping"                => "base#ping"
      post "csp-report"          => "base#csp_report"
      get  "geoip(/:ip)"         => "base#geoip", constraints: { ip: %r{[^\/]+} } # accept IP including dots

      post "/customers/sign_in"
      resources :customers,         only: [:index, :show, :create, :update]
      resources :boxes,             only: [:index, :show]
      resources :delivery_services, only: [:index, :show]
      resources :orders,            only: [:index, :show, :create]
      resources :webstores,         only: [:index] # all webstores
      resource  :webstore,          only: [:show] # current webstore
      resources :deliveries,        only: [:index] do
        get :pending, on: :collection
      end
    end
  end

  # TODO: Legacy routes. As we move to all RESTful routes these should be removed.
  get "/distributor/deliveries/date/:date/view/:view",            controller: "distributor/deliveries", action: :index,                           as: "date_distributor_deliveries"
  post "/distributor/deliveries/date/:date/reposition",           controller: "distributor/deliveries", action: :reposition,                      as: "reposition_distributor_deliveries"
  post "/distributor/deliveries/update_status",                   controller: "distributor/deliveries", action: :update_status,                   as: "update_status_distributor_deliveries"
  post "/distributor/deliveries/make_payment",                    controller: "distributor/deliveries", action: :make_payment,                    as: "make_payment_distributor_deliveries"
  post "/distributor/deliveries/master_packing_sheet",            controller: "distributor/deliveries", action: :master_packing_sheet,            as: "master_packing_sheet_distributor_deliveries"

  post "/distributor/deliveries/export",                          controller: "distributor/export/deliveries",               action: :index, as: "export_distributor_deliveries"
  post "/distributor/deliveries/export_extras",                   controller: "distributor/export/extras",                   action: :index, as: "export_extras_distributor_deliveries"
  post "/distributor/deliveries/export_exclusions_substitutions", controller: "distributor/export/exclusions_substitutions", action: :index, as: "export_exclusions_substitutions_distributor_deliveries"
end

app/models/distributor/form.rb
require 'virtus'
require 'active_support/concern'
require 'active_model/naming'
require 'active_model/conversion'
require 'active_model/validations'
require 'active_model/translation'

module Distributor::Form
  extend ActiveSupport::Concern

  included do
    extend ActiveModel::Naming

    include Virtus.model
    include ActiveModel::Conversion
    include ActiveModel::Validations

    attribute :distributor,  Integer
    attribute :customer,     Integer

    delegate :id, to: :customer

    def initialize(attributes = {})
      @distributor = attributes.delete(:distributor)
      @customer    = attributes.delete(:customer)
      super
      assign_attributes(attributes)
    end

    def persisted?
      true
    end

    def save
      return false unless valid?

      success = customer.update_attributes(customer_args) &&
                address.update_attributes(address_args)

      forward_errors_to_form customer
      forward_errors_to_form address

      success
    end

  protected

    def forward_errors_to_form(model)
      model.errors.each do |attribute, message|
        errors.add(attribute, message)
      end
    end

    def address
      @address ||= begin
        customer.address || Address.new
      end
    end

    def assign_attributes(_attributes)
      # No Op
    end

    def customer_args
      {}
    end

    def address_args
      {}
    end
  end
end

app/models/distributor/form/edit_customer_delivery_details.rb
require_relative "edit_customer_delivery_details_fields"

class Distributor::Form::EditCustomerDeliveryDetails
  include Distributor::Form::EditCustomerDeliveryDetailsFields

protected

  def customer_args
    delivery_details_customer_args
  end

  def address_args
    delivery_details_address_args
  end
end

app/models/distributor/form/edit_customer_delivery_details_fields.rb
require 'active_support/concern'
require_relative "../form"

module Distributor::Form::EditCustomerDeliveryDetailsFields
  extend ActiveSupport::Concern
  include Distributor::Form
  include Customer::AddressValidations

  included do
    attribute :delivery_service_id, Integer

    delegate :collect_delivery_note?, :delivery_services, to: :distributor

    validates_presence_of :delivery_service_id

  protected

    def assign_attributes(attributes)
      @delivery_service_id = attributes["delivery_service_id"] || customer.delivery_service_id
      @address_1           = attributes["address_1"] || address.address_1
      @address_2           = attributes["address_2"] || address.address_2
      @suburb              = attributes["suburb"] || address.suburb
      @city                = attributes["city"] || address.city
      @postcode            = attributes["postcode"] || address.postcode
      @delivery_note       = attributes["delivery_note"] || address.delivery_note
    end

    def delivery_details_customer_args
      {
        delivery_service_id: delivery_service_id,
      }
    end

    def delivery_details_address_args
      {
        address_1:      address_1,
        address_2:      address_2,
        suburb:         suburb,
        city:           city,
        postcode:       postcode,
        delivery_note:  delivery_note,
      }
    end
  end
end

app/models/distributor/form/edit_customer_profile.rb
require_relative "edit_customer_profile_fields"

class Distributor::Form::EditCustomerProfile
  include Distributor::Form::EditCustomerProfileFields

protected

  def customer_args
    profile_customer_args
  end

  def address_args
    profile_address_args
  end
end

app/models/distributor/form/new_customer.rb
require_relative "edit_customer_profile_fields"

class Distributor::Form::NewCustomer
  include Distributor::Form::EditCustomerProfileFields
  include Distributor::Form::EditCustomerDeliveryDetailsFields

protected

  def customer_args
    args = profile_customer_args.merge(delivery_details_customer_args)
    args.merge(distributor: distributor)
  end

  def address_args
    args = profile_address_args.merge(delivery_details_address_args)
    args.merge(customer: customer)
  end
end

app/controllers/admin/distributors_controller.rb
class Admin::DistributorsController < Admin::ResourceController
  before_action :parameterize_name, only: [:create, :update]

  def index
    recent_delay = 6.months.ago
    @distributors = Distributor.where(
      "last_seen_at > ? OR created_at > ?", recent_delay, recent_delay
    ).order("last_seen_at DESC, created_at DESC")
    @distributors = @distributors.tagged_with(params[:tag]) if params[:tag].present?
    @hidden_distributors = Distributor.count - @distributors.count
    index!
  end

  def create
    create! do |success, _failure|
      success.html do
        Distributor::Defaults.populate_defaults(@distributor)
        redirect_to admin_root_url
      end
    end
  end

  def update
    update! do |success, _failure|
      success.html do
        redirect_to admin_root_url
      end
    end
  end

  def impersonate
    distributor = Distributor.find(params[:id])
    sign_in(distributor, bypass: true) # bypass means it won't update last logged in stats

    redirect_to distributor_root_url
  end

  def unimpersonate
    sign_out(:distributor)

    redirect_to admin_root_url
  end

  def country_setting
    @country = Country.find(params[:id])

    time_zone = ActiveSupport::TimeZone::MAPPING.find do |_, city|
      city == @country.time_zone
    end
    time_zone = time_zone.first if time_zone

    render json: {
      time_zone: time_zone,
      currency: @country.currency,
      fee: @country.default_consumer_fee_cents / 100.0,
    }
  end

private

  def parameterize_name
    if params[:distributor]
      parameterized_name = Distributor.parameterize_name(params[:distributor][:parameter_name])
      params[:distributor][:parameter_name] = parameterized_name
    end
  end
end

app/controllers/distributor/accounts_controller.rb
class Distributor::AccountsController < Distributor::ResourceController
  respond_to :html, :json

  def change_balance
    @account = Account.find(params[:id])

    respond_to do |format|
      if create_transaction(@account, params)
        format.html { redirect_to [:distributor, @account.customer], notice: 'Account balance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to [:distributor, @account.customer] }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def transactions
    offset_size = 0
    limit = params[:limit].to_i
    limit ||= 6

    limit += 100 if params[:more].present?
    @account = current_distributor.accounts.find(params[:id])
    @transactions = account_transactions(@account, offset_size, limit)
    @show_more_link = @transactions.size != @account.transactions.count

    @transactions_sum = @account.calculate_balance(offset_size)

    render partial: 'distributor/transactions/index'
  end

private

  def create_transaction(account, params)
    opts = {}
    delta = CrazyMoney.new(params[:delta])

    if delta.zero?
      flash[:error] = 'Change in balance must be a number and not zero.'
    else
      opts[:delta] = delta
    end

    opts[:description] = params[:note] if params[:note].present?

    if params[:date].present?
      opts[:display_time] = Date.parse(params[:date]).to_time_in_current_zone
    end

    !delta.zero? && account.create_transaction(delta, opts)
  end
end

app/controllers/distributor/base_controller.rb
class Distributor::BaseController < ApplicationController
  layout 'distributor'

  before_action :authenticate_distributor!
  before_action :mark_as_seen
  before_action :notifications
  before_action :distributor_setup
  before_action :check_if_very_overdue

private

  def mark_as_seen
    Distributor.mark_as_seen!(current_distributor, no_track: current_admin.present?)
  end

  def notifications
    @notifications ||= Event.all_for_distributor(current_distributor)
  end

  def distributor_setup
    @distributor_setup ||= Distributor::Setup.new(current_distributor)
  end

  def check_setup
    redirect_to distributor_root_url and return unless distributor_setup.finished_settings?
  end

  def check_if_very_overdue
    # redirect to billing if more than 1 overdue invoice
    if current_distributor.overdue.count("\n").positive? && request.path != distributor_billing_path
      redirect_to distributor_billing_path and return
    end
  end
end

app/controllers/distributor/billing_controller.rb
class Distributor::BillingController < Distributor::BaseController
  def show
    last_invoices = current_distributor.invoices.order('distributor_invoices.to').last(5).reverse
    current_pricing = current_distributor.pricing
    next_pricing = Distributor::Pricing.where(distributor_id: current_distributor.id).last
    other_pricings = current_pricing.pricings_for_currency.reject do |pricing|
      (next_pricing && next_pricing == pricing) || (!next_pricing && current_pricing == pricing)
    end

    render locals: {
      current_pricing: current_pricing,
      next_pricing: next_pricing,
      other_pricings: other_pricings,
      invoices: last_invoices,
    }
  end
end

app/views/distributor/settings/_payments.html.haml
- title("Payments", false)
- show_settings_sub_nav(:bank_info)

#payments.tabbable.tabs-left
  %ul.nav.nav-tabs
    - Distributor.all_payment_options.each do |payment_option_key, payment_option_label|
      - payment_option_label = "PayPal" if payment_option_key == :paypal # hack
      %li{ class: "#{'active' if type == payment_option_key}" }
        - path = public_send "distributor_settings_payments_#{payment_option_key}_path"
        = link_to path do
          = payment_option_label
          - if current_distributor.public_send("payment_#{payment_option_key}")
            %i.icon.icon-ok-sign.pull-right{title: 'Enabled'}

  .tab-content
    = yield(:payment_type)

app/views/distributor/settings/_products.html.haml
- title "#{type.singularize.titleize} Settings", false
- show_settings_sub_nav

#products.tabbable.tabs-left
  %ul.nav.nav-tabs
    %li{ class: "#{'active' if type == 'boxes'}" }= link_to "Boxes", distributor_settings_products_boxes_path
    %li{ class: "#{'active' if type == 'box_items'}" }= link_to "Box Items", distributor_settings_products_box_items_path
    %li{ class: "#{'active' if type == 'extra_items'}" }= link_to "Extra Items", distributor_settings_products_extra_items_path

  .tab-content{ class: type }
    = yield(:product_type)

app/views/distributor/settings/_sub_nav.html.haml
%ul.nav-pills
  = sub_tab 'Organisation',      distributor_settings_organisation_path,              { force_highlighted: force_highlighted }
  = sub_tab 'Web Store',         distributor_settings_webstore_path,                  { force_highlighted: force_highlighted }
  = sub_tab 'Delivery Services', distributor_settings_delivery_services_path,         { force_highlighted: force_highlighted }
  = sub_tab 'Products',          distributor_settings_products_boxes_path,            { force_highlighted: force_highlighted }
  = sub_tab 'Payments',          distributor_settings_payments_cash_on_delivery_path, { force_highlighted: force_highlighted }

app/views/distributor/settings/delivery_services.html.haml
- title 'Delivery Service Settings', false
- show_settings_sub_nav

#delivery_services
  .delivery_services
    .row-fluid
      .span6
        Your organisation will use one or more Delivery Services to deliver to customers.
        Each of your customers will be assigned to a Delivery Service that best services their location.
      .span6
        %span.heading hint
        It's best to name your Delivery Service according to the geographic region it services e.g. Inner City, Southern Suburbs.
        Customers on Pickup Points will not be asked for their address
        #{link_to "(more info)", 'http://help.buckybox.com/user-manual/setting-up/delivery-services/', target: '_blank'}.

    %table.table.table-condensed.spacer#delivery_services
      %tr
        %td{colspan: 4}
          - first_delivery_service = delivery_services.one?
          = link_to 'javascript:void(0)', class: (first_delivery_service ? 'required-action' : 'action'), 'data-toggle' => 'collapse', 'data-target' => '#new_delivery_service' do
            Create
            = first_delivery_service ? 'your first' : 'a new'
            <strong>Delivery Service</strong>

      - delivery_services.each do |delivery_service|
        - if delivery_service.persisted?
          %tr{ 'data-toggle' => 'collapse', 'data-target' => "#edit_delivery_service_#{delivery_service.id}" }
            %td.name
              %strong= link_to delivery_service.name, 'javascript:void(0)'
              %em.muted.instructions= truncate(delivery_service.instructions, length: [80 - delivery_service.name.length, 10].max)
            %td.pickup_point
              - if delivery_service.pickup_point
                %i.icon-map-marker.text-right{ title: "This is a pickup point" }
            %td.days
              = delivery_service.delivery_days
            %td.fee
              %span= delivery_service.formatted_fee

        %tr.edit
          %td{colspan: 4}
            = simple_form_for(delivery_service, url: distributor_settings_delivery_services_path, html: { novalidate: false, class: 'collapse background-yellow' }) do |f|
              = f.hidden_field :id if delivery_service.id
              = f.hidden_field :delete, value: 0

              .container-fluid
                .line
                  = f.input_field :name, class: 'name', required: true, placeholder: 'Delivery Service Name'

                  %span#weekdays.days.text-center
                    = f.simple_fields_for(:schedule_rule) do |schedule_rule_form|
                      - %i(mon tue wed thu fri sat sun).each do |day|
                        = schedule_rule_form.input_field day, inline_label: true, label: "<br><span class='label label-default'>#{day}</span>".html_safe, "data-original-checked" => (delivery_service.public_send(day) ? "checked" : "")

                  = f.input_field :fee, class: 'fee pull-right', required: true, placeholder: CrazyMoney.zero, title: 'Fee'
                .line
                  = f.input_field :instructions, class: 'instructions pull-left', required: true, placeholder: "Delivery Service Details i.e. instructions to customers including area of service for deliveries, estimated delivery or pickup times", rows: 8
                  %span.pickup_point
                    = f.input_field :pickup_point, inline_label: true, label: "<i class='icon-map-marker'></i> This is a <strong>Pickup Point</strong>".html_safe

                .line.clearfix

                .form-actions.pull-right
                  = link_to 'cancel', 'javascript:void(0)', 'data-toggle' => 'collapse', 'data-target' => (delivery_service.new_record? ? "#new_delivery_service" : "#edit_delivery_service_#{delivery_service.id}")

                  - if delivery_service.persisted?
                    &nbsp;
                    - if delivery_service.customers.empty?
                      = link_to_function "delete", "$(this).closest('form').find('input[id=delivery_service_delete]').val(1).closest('form').submit()"
                    - else
                      = link_to 'delete', 'javascript:void(0)', onclick: "alert('You must reassign #{pluralize(delivery_service.customers.count, "customer")} before deleting this delivery service.');"

                  = f.button :submit, 'Save', class: 'btn btn-primary', 'data-conditional-confirm' => "A day has been unchecked. Customer orders on this day will be DELETED. Are you sure?"

app/views/distributor/settings/extras.html.haml
- title 'Extras Catalog'
- show_settings_sub_nav

= render partial: 'distributor/extras/index'

%h3 Add extra
.row-fluid
  .span12
    Extras are additional sale items that can be included for delivery with a box.
%br
.row-fluid
  = render partial: 'distributor/extras/form'

app/views/distributor/settings/webstore.html.haml
- title 'Webstore', false
- show_settings_sub_nav(:web_store)

#webstore-settings
  .row-fluid
    .span12
      Your web store is currently set up in #{I18n.t('current_locale_en', locale: current_distributor.locale)}, please
      = mail_to "support@buckybox.com", "contact us"
      to change it.

  = simple_form_for(@form, url: distributor_settings_webstore_url) do |f|
    .important_action{class: @form.webstore_enabled ? 'green' : 'red'}
      = f.input :webstore_enabled, as: :boolean, inline_label: "Activate the <strong>Web Store</strong>".html_safe, label: false

    .row-fluid
      .span6.column-left
        %fieldset.org_banner
          .row-fluid.header
            .span12
              .pull-left
                .blue-circle
                  .blue-inner-circle
                    1
              .pull-left.title Organisation Banner
          .row-fluid.body
            .hidden
              = f.input_field :org_banner_file, as: :file, style: 'display: none'
              = f.input_field :org_banner_file_cache, as: :hidden
            - if current_distributor.company_logo?
              .image-box
                #org_banner_file_upload.image-rollover
                  .image-message
                    update image
                    960px x 160px
                = image_tag(current_distributor.company_logo.frame_banner.url, id: "org_banner_file_upload", class: 'image-upload banner')
            - else
              #org_banner_file_upload
                .banner
                  .banner-description
                    %strong Your organisation's banner
                    Appears on your customer login page and Web Store
                    960px x 160px

        %fieldset.team_photo
          .row-fluid.header
            .span12
              .pull-left
                .blue-circle
                  .blue-inner-circle
                    2
              .pull-left.title Team Photo
          .row-fluid.body
            .hidden
              = f.input_field :team_photo_file, as: :file, style: 'display: none'
              = f.input_field :team_photo_file_cache, as: :hidden
            - if current_distributor.company_team_image?
              .image-box
                #team_photo_file_upload.image-rollover
                  .image-message
                    update image
                    420px x 280px
                = image_tag(current_distributor.company_team_image.half_size_photo.url, id: "team_photo_file_upload", class: 'image-upload banner')
            - else
              #team_photo_file_upload
                .banner
                  .banner-description
                    %strong Your team photo
                    Appears on your Web Store sidebar
                    %br
                    420px x 280px

        %fieldset.sidebar_description
          .row-fluid.header
            .span12
              .pull-left
                .blue-circle
                  .blue-inner-circle
                    3
              .pull-left.title Sidebar Description
          .row-fluid.body
            = f.input_field :sidebar_description, as: :text, placeholder: "Our Eco-farm was born out of a desire to produce quality...", label: false, rows: 10

        %fieldset.sidebar_description
          .row-fluid.header
            .span12
              .pull-left
                .blue-circle
                  .blue-inner-circle
                    4
              .pull-left.title Other Details
          .row-fluid.body
            .facebook_link
              .input-prepend.input-block-level
                %span.add-on
                  %i.icon-face
                = f.input_field :facebook, placeholder: "Facebook page URL", label: false
            .phone
              .input-prepend.input-block-level
                %span.add-on
                  %i.icon-cellphone
                = f.input_field :phone, placeholder: "Customer service phone number", label: false

      .span6.column-right.hidden-phone
        .row-fluid
          .span12.image-overlay
            = image_tag("webstore-preview.jpg")
            .overlay.one
              .blue-circle
                .blue-inner-circle
                  1
            .overlay.two
              .blue-circle
                .blue-inner-circle
                  2
            .overlay.three
              .blue-circle
                .blue-inner-circle
                  3
            .overlay.four
              .blue-circle
                .blue-inner-circle
                  4

    .row-fluid.line-break
      .span12
        .pull-right
          = f.submit 'Save', class: 'btn btn-primary'