config/routes.rb
API_SUBDOMAIN = { subdomain: /\A(staging-)?api\Z/ }.freeze unless defined? API_SUBDOMAIN

BuckyBox::Application.routes.draw do
  apipie

  devise_for :admins,       controllers: { sessions: "admin/sessions" }
  devise_for :distributors, controllers: { sessions: "distributor/sessions", passwords: "distributor/passwords" }
  devise_for :customers,    controllers: { sessions: "customer/sessions", passwords: "customer/passwords" }

  get "/ping" => "application#ping"
  get "/delayed_job" => DelayedJobWeb, anchor: false
  get "/" => "api#index", constraints: API_SUBDOMAIN

  root to: "distributor/customers#index"

  namespace :sign_up_wizard do
    get "form"
    get "country"
    post "sign_up"
  end

  namespace :distributor do
    root to: "welcome#index"

    namespace :settings do
      get "organisation"
      get "webstore"
      post "webstore", action: "save_webstore"
      post "spend_limit_confirmation"

      resource :delivery_services, only: [:show, :create, :update, :destroy]

      namespace :products do
        resource :boxes, only: [:show, :create, :update]
        resource :box_items, only: [:show, :create, :update]
        resource :extra_items, only: [:show, :create, :update]
      end

      namespace :payments do
        resource :bank_deposit, controller: "bank_deposit", only: [:show, :update]
        resource :cash_on_delivery, controller: "cash_on_delivery", only: [:show, :update]
        resource :paypal, controller: "paypal", only: [:show, :update]
      end
    end

    namespace :notifications do
      post "dismiss_all", actions: "dismiss_all", as: "dismiss_all"
    end

    namespace :intro_tour do
      post "dismiss", actions: "dismiss", as: "dismiss"
    end

    namespace :reports do
      get "/",                               action: "index"
      get "transaction_history/:start/:to",  action: "transaction_history",      as: "transaction_history"
      get "customer_account_history/:to",    action: :customer_account_history,  as: "customer_account_history"
    end

    resource :billing, only: :show, controller: "billing"
    resource :pricing, only: :update, controller: "pricing"

    resources :distributors,        only: :update
    resource  :bank_information,    only: :update
    resources :boxes,               except: [:index]
    resources :extras,              except: [:index, :show]

    resources :line_items, except: [:index, :show, :update] do
      collection do
        put "bulk_update", action: :bulk_update, as: "bulk_update"
      end
    end

    resources :deliveries

    resources :payments, only: [:index, :destroy] do
      collection do
        post "match_payments", action: "match_payments", as: "match_payments"
      end

      member do
        put "process_payments", action: "process_payments", as: "process_payments"
      end
    end

    resources :import_transactions, only: [:update] do
      member do
        get "load_more_rows/:position", action: "load_more_rows", as: "load_more_rows"
      end
    end

    resources :import_transaction_lists, only: [:destroy]

    resources :customers, except: [:edit] do
      collection do
        get "search",   action: :index, as: "search"
        get "tag/:tag", action: :index, as: "tag"
        post "email"
        post "export"
      end

      member do
        get :send_login_details
        get "impersonate"
        get "activity"
        get "edit_profile",             action: "edit_profile",             as: "edit_profile"
        put "update_profile",           action: "update_profile",           as: "update_profile"
        get "edit_delivery_details",    action: "edit_delivery_details",    as: "edit_delivery_details"
        put "update_delivery_details",  action: "update_delivery_details",  as: "update_delivery_details"
      end
    end

    resources :accounts, only: :edit do
      resources :orders, except: [:index, :show, :destroy] do
        member do
          put "deactivate"
          put "pause"
          post "remove_pause"
          put "resume"
          post "remove_resume"
        end
      end

      resources :boxes do
        member do
          get "extras"
        end
      end

      member do
        put "change_balance", action: :change_balance, as: "change_balance"
        get "transactions/:limit(/:more)", action: :transactions, as: "transactions"
        get "receive_payment", action: :receive_payment, as: "receive_payment"
        post "save_payment",   action: :save_payment, as: "save_payment"
      end
    end
  end

  namespace :customer do
    root to: "dashboard#index"

    get "dashboard",               controller: "dashboard", action: "index"
    get "order/:order_id/box/:id", controller: "dashboard", action: "box"

    put "update_contact_details",   controller: "customers",  action: "update_contact_details"
    put "update_delivery_address",  controller: "customers",  action: "update_delivery_address"
    put "update_password",          controller: "customers",  action: "update_password"

    resources :boxes, only: [:show] do
      member do
        get "extras"
      end
    end

    resources :orders, only: [:edit, :update] do
      member do
        put "pause"
        post "remove_pause"
        put "resume"
        post "remove_resume"
        put "deactivate"
      end
    end

    resources :accounts, only: [] do
      get "transactions/:limit(/:more)", action: :transactions, as: "transactions"
    end
  end

  namespace :admin do
    root to: "dashboard#index"

    resources :cron_logs, only: :index
    resources :style_sheet, only: :index

    resources :metrics, only: [:index] do
      collection do
        get "transactional_customers"
        get "sales"
      end
    end

    resources :distributors, only: [:index, :new, :create, :edit, :update] do
      member do
        get "impersonate"
      end

      collection do
        get "unimpersonate"
        get "country_setting/:id", controller: "distributors", action: "country_setting"
        get "tag/:tag", action: :index, as: "tag"
      end
    end

    resources :omni_importers do
      member do
        post "test"
      end
    end
  end

  namespace :api, path: "", defaults: { format: :json }, constraints: API_SUBDOMAIN do
    namespace :v1 do
      get  "ping"                => "base#ping"
      post "csp-report"          => "base#csp_report"
      get  "geoip(/:ip)"         => "base#geoip", constraints: { ip: %r{[^\/]+} } # accept IP including dots

      post "/customers/sign_in"
      resources :customers,         only: [:index, :show, :create, :update]
      resources :boxes,             only: [:index, :show]
      resources :delivery_services, only: [:index, :show]
      resources :orders,            only: [:index, :show, :create]
      resources :webstores,         only: [:index] # all webstores
      resource  :webstore,          only: [:show] # current webstore
      resources :deliveries,        only: [:index] do
        get :pending, on: :collection
      end
    end
  end

  # TODO: Legacy routes. As we move to all RESTful routes these should be removed.
  get "/distributor/deliveries/date/:date/view/:view",            controller: "distributor/deliveries", action: :index,                           as: "date_distributor_deliveries"
  post "/distributor/deliveries/date/:date/reposition",           controller: "distributor/deliveries", action: :reposition,                      as: "reposition_distributor_deliveries"
  post "/distributor/deliveries/update_status",                   controller: "distributor/deliveries", action: :update_status,                   as: "update_status_distributor_deliveries"
  post "/distributor/deliveries/make_payment",                    controller: "distributor/deliveries", action: :make_payment,                    as: "make_payment_distributor_deliveries"
  post "/distributor/deliveries/master_packing_sheet",            controller: "distributor/deliveries", action: :master_packing_sheet,            as: "master_packing_sheet_distributor_deliveries"

  post "/distributor/deliveries/export",                          controller: "distributor/export/deliveries",               action: :index, as: "export_distributor_deliveries"
  post "/distributor/deliveries/export_extras",                   controller: "distributor/export/extras",                   action: :index, as: "export_extras_distributor_deliveries"
  post "/distributor/deliveries/export_exclusions_substitutions", controller: "distributor/export/exclusions_substitutions", action: :index, as: "export_exclusions_substitutions_distributor_deliveries"
end

app/models/concerns/customer/address_validations.rb
require 'active_support/concern'

module Customer::AddressValidations
  extend ActiveSupport::Concern

  included do
    attribute :address_1,           String
    attribute :address_2,           String
    attribute :suburb,              String
    attribute :city,                String
    attribute :postcode,            String
    attribute :delivery_note,       String

    validates_presence_of :address_1,      if: -> { require_address_1 }
    validates_presence_of :address_2,      if: -> { require_address_2 }
    validates_presence_of :suburb,         if: -> { require_suburb }
    validates_presence_of :city,           if: -> { require_city }
    validates_presence_of :postcode,       if: -> { require_postcode }
    validates_presence_of :delivery_note,  if: -> { require_delivery_note }

    def delivery_service
      new_delivery_service || customer.delivery_service
    end

    def pickup_point?
      delivery_service && delivery_service.pickup_point?
    end

    def require_address_1
      !pickup_point? && distributor.require_address_1
    end

    def require_address_2
      !pickup_point? && distributor.require_address_2
    end

    def require_suburb
      !pickup_point? && distributor.require_suburb
    end

    def require_city
      !pickup_point? && distributor.require_city
    end

    def require_postcode
      !pickup_point? && distributor.require_postcode
    end

    def require_delivery_note
      !pickup_point? && distributor.require_delivery_note
    end

  private

    def new_delivery_service
      return unless self.respond_to?(:delivery_service_id)

      DeliveryService.find(delivery_service_id) if delivery_service_id
    end
  end
end

app/models/concerns/customer/phone_validations.rb
require 'active_support/concern'

module Customer::PhoneValidations
  extend ActiveSupport::Concern

  included do
    attribute :mobile_phone
    attribute :home_phone
    attribute :work_phone

    validate :validate_phone

  private

    def validate_phone
      if distributor.require_phone && PhoneCollection.attributes.all? { |type| self[type].blank? }
        errors[:phone_number] << "can't be blank"
      end
    end
  end
end

app/models/customer/form.rb
require 'virtus'
require 'active_model/naming'
require 'active_model/conversion'
require 'active_model/validations'
require 'active_model/translation'

class Customer::Form
  extend ActiveModel::Naming

  include Virtus.model
  include ActiveModel::Conversion
  include ActiveModel::Validations

  attribute :customer

  delegate :id, :address, :distributor, to: :customer

  def initialize(attributes = {})
    @customer = attributes.delete("customer")
    super
    assign_attributes(attributes)
  end

  def persisted?
    true
  end

  # Overwrite i18n_scope from activemodel/lib/active_model/translation.rb
  def self.i18n_scope
    :virtus
  end

protected

  def assign_attributes(_attributes)
    # just a NO OP hook
  end
end

app/models/customer/form/update_contact_details.rb
require_relative "../form"

class Customer::Form::UpdateContactDetails < Customer::Form
  include Customer::PhoneValidations

  attribute :first_name
  attribute :last_name
  attribute :email

  delegate :require_phone?, :collect_phone?, to: :distributor

  validates_presence_of :first_name
  validates_presence_of :email

  def save
    return false unless self.valid?

    customer.update_attributes(customer_args) &&
      address.update_attributes(address_args)
  end

protected

  def assign_attributes(attributes)
    @first_name   = attributes["first_name"] || customer.first_name
    @last_name    = attributes["last_name"] || customer.last_name
    @email        = attributes["email"] || customer.email
    @mobile_phone = attributes["mobile_phone"] || address.mobile_phone
    @home_phone   = attributes["home_phone"] || address.home_phone
    @work_phone   = attributes["work_phone"] || address.work_phone
  end

private

  def customer_args
    {
      first_name:  first_name,
      last_name:   last_name,
      email:       email,
    }
  end

  def address_args
    {
      mobile_phone:  mobile_phone,
      home_phone:    home_phone,
      work_phone:    work_phone,
    }
  end
end

app/models/customer/form/update_delivery_address.rb
require_relative "../form"

class Customer::Form::UpdateDeliveryAddress < Customer::Form
  include Customer::AddressValidations

  delegate :collect_delivery_note?, to: :distributor

  def save
    return false unless valid?

    customer.update_address(address_args, notify_distributor: true)
  end

protected

  def assign_attributes(attributes)
    @address_1     = attributes["address_1"] || address.address_1
    @address_2     = attributes["address_2"] || address.address_2
    @suburb        = attributes["suburb"] || address.suburb
    @city          = attributes["city"] || address.city
    @postcode      = attributes["postcode"] || address.postcode
    @delivery_note = attributes["delivery_note"] || address.delivery_note
  end

private

  def address_args
    {
      address_1:      address_1,
      address_2:      address_2,
      suburb:         suburb,
      city:           city,
      postcode:       postcode,
      delivery_note:  delivery_note,
    }
  end
end

app/models/customer/form/update_password.rb
require_relative "../form"

class Customer::Form::UpdatePassword < Customer::Form
  attribute :password
  attribute :password_confirmation

  validates_presence_of :password
  validates_presence_of :password_confirmation

  def save
    return false unless self.valid?

    if customer.update_attributes(customer_args)
      true
    else
      @errors = customer.errors
      false
    end
  end

private

  def customer_args
    {
      password:               password,
      password_confirmation:  password_confirmation,
    }
  end
end

app/models/distributor/form.rb
require 'virtus'
require 'active_support/concern'
require 'active_model/naming'
require 'active_model/conversion'
require 'active_model/validations'
require 'active_model/translation'

module Distributor::Form
  extend ActiveSupport::Concern

  included do
    extend ActiveModel::Naming

    include Virtus.model
    include ActiveModel::Conversion
    include ActiveModel::Validations

    attribute :distributor,  Integer
    attribute :customer,     Integer

    delegate :id, to: :customer

    def initialize(attributes = {})
      @distributor = attributes.delete(:distributor)
      @customer    = attributes.delete(:customer)
      super
      assign_attributes(attributes)
    end

    def persisted?
      true
    end

    def save
      return false unless valid?

      success = customer.update_attributes(customer_args) &&
                address.update_attributes(address_args)

      forward_errors_to_form customer
      forward_errors_to_form address

      success
    end

  protected

    def forward_errors_to_form(model)
      model.errors.each do |attribute, message|
        errors.add(attribute, message)
      end
    end

    def address
      @address ||= begin
        customer.address || Address.new
      end
    end

    def assign_attributes(_attributes)
      # No Op
    end

    def customer_args
      {}
    end

    def address_args
      {}
    end
  end
end

app/models/distributor/form/edit_customer_delivery_details.rb
require_relative "edit_customer_delivery_details_fields"

class Distributor::Form::EditCustomerDeliveryDetails
  include Distributor::Form::EditCustomerDeliveryDetailsFields

protected

  def customer_args
    delivery_details_customer_args
  end

  def address_args
    delivery_details_address_args
  end
end

app/models/distributor/form/edit_customer_delivery_details_fields.rb
require 'active_support/concern'
require_relative "../form"

module Distributor::Form::EditCustomerDeliveryDetailsFields
  extend ActiveSupport::Concern
  include Distributor::Form
  include Customer::AddressValidations

  included do
    attribute :delivery_service_id, Integer

    delegate :collect_delivery_note?, :delivery_services, to: :distributor

    validates_presence_of :delivery_service_id

  protected

    def assign_attributes(attributes)
      @delivery_service_id = attributes["delivery_service_id"] || customer.delivery_service_id
      @address_1           = attributes["address_1"] || address.address_1
      @address_2           = attributes["address_2"] || address.address_2
      @suburb              = attributes["suburb"] || address.suburb
      @city                = attributes["city"] || address.city
      @postcode            = attributes["postcode"] || address.postcode
      @delivery_note       = attributes["delivery_note"] || address.delivery_note
    end

    def delivery_details_customer_args
      {
        delivery_service_id: delivery_service_id,
      }
    end

    def delivery_details_address_args
      {
        address_1:      address_1,
        address_2:      address_2,
        suburb:         suburb,
        city:           city,
        postcode:       postcode,
        delivery_note:  delivery_note,
      }
    end
  end
end

app/views/distributor/customers/_activity.html.haml
%ul
  - activities.each do |activity|
    %li
      %strong #{timeago_tag activity.created_at}
      = "- #{activity.action}."

app/views/distributor/customers/_controls.html.haml
- content_for :sub_nav do
  .row-fuild
    .action-buttons.span3
      - unless defined? @customers
        .btn-group
          = link_to distributor_customers_path, { class: "btn", title: "Back to customer list" } do
            %i.icon-arrow-left

      - else
        .btn-group
          = button_tag class: 'btn btn-primary' do
            = check_box_tag 'select_all'
          = button_tag class: "btn btn-primary dropdown-toggle", data: { toggle: 'dropdown' } do
            %span.caret
          %ul.dropdown-menu{ role: 'menu' }
            %li
              = link_to 'javascript:void(0)', id: 'select_all-all' do
                All
            %li
              = link_to 'javascript:void(0)', id: 'select_all-none' do
                None
            %li
              = link_to 'javascript:void(0)', id: 'select_all-inverse' do
                Inverse

      .btn-group{:class => ("conditional-actions" if defined? @customers)}
        = link_to "#distributor_send_email", class: "btn btn-primary", title: "Send an email", role: "button", "data-toggle" => "modal" do
          %i.icon-envelope.icon-white
        = button_tag class: "btn btn-primary dropdown-toggle", data: { toggle: 'dropdown' } do
          %span.caret
        %ul.dropdown-menu{ role: 'menu' }
          - if defined? @customers
            %li
              = link_to "#distributor_copy_email", "data-toggle" => "modal" do
                View as email addresses
          %li
            = link_to "Export customer details", "#distributors_customers_export", id: "export_customer_details"

    #search-form.span6
      = form_tag search_distributor_customers_path, method: :get do
        .input-append
          = text_field_tag :query, params[:query], placeholder: 'Customer Number, name, address...', class: 'span10'
          = button_tag type: 'submit', class: 'btn btn-primary' do
            %i.icon-search.icon-white

      - if params[:query]
        .brand
          Searching
          %strong= params[:query]
          %small= link_to 'clear', distributor_customers_path
      - elsif params[:tag]
        .brand
          Tag
          %strong= params[:tag]
          %small= link_to 'clear', distributor_customers_path

    .span3
      / future settings drop-down

= render partial: "distributor/shared/email_templates"
= render partial: "customer_export_form"

app/views/distributor/customers/_customer_export_form.html.haml
= simple_form_for(:export, url: export_distributor_customers_path, html: {style:'display: none;', id: 'export_customer_details_form'}) do |f|
  = f.input :recipient_ids, as: :hidden

app/views/distributor/customers/_edit_delivery_details_inputs.html.haml
.row-fluid
  .span6
    = f.input :delivery_service_id, collection: delivery_details.delivery_services, include_blank: false, input_html: { class: "input-block-level" }
    = f.input :address_1,           required: delivery_details.require_address_1, input_html: { class: "input-block-level" }
    = f.input :address_2,           required: delivery_details.require_address_2, input_html: { class: "input-block-level" }
    = f.input :suburb,              required: delivery_details.require_suburb, input_html: { class: "input-block-level" }
    = f.input :city,                required: delivery_details.require_city, input_html: { class: "input-block-level" }
    = f.input :postcode,            required: delivery_details.require_postcode, input_html: { class: "input-block-level" }

  .span6
    = f.input :delivery_note, as: :text, placeholder: "Delivery instructions such as where to place the package, e.g. Place on back porch", input_html: { class: "input-block-level" }

app/views/distributor/customers/_edit_profile_inputs.html.haml
.row-fluid
  .span6
    - unless customer_profile.auto_assign_number?
      = f.input :number,  as: :integer,  input_html: { class: "input-block-level" }

    = f.input :first_name,    input_html: { class: "input-block-level" }
    = f.input :last_name,     input_html: { class: "input-block-level" }
    = f.input :tag_list,      label: "Tags",  placeholder: "E.g. west-end, coupon, discount",  input_html: { class: "input-block-level" }
    = f.input :email,         input_html: { class: "input-block-level" }

    - if customer_profile.require_phone?
      %p.muted At least one type of phone number is required
    = f.input :mobile_phone,  input_html: { class: "input-block-level" }
    = f.input :home_phone,    input_html: { class: "input-block-level" }
    = f.input :work_phone,    input_html: { class: "input-block-level" }

    - if customer_profile.has_balance_threshold?
      = f.input :balance_threshold,  as: :decimal,  label: "Minimum balance",  hint: "Deliveries will halt when their balance reaches the minimum balance.",  input_html: { class: "input-block-level",  step: 0.01 }

    = f.input :discount,  as: :decimal,  input_html: { class: "input-block-level",  step: 0.0001 }

  .span6
    = f.input :special_order_preference,  as: :text,  label: "Packing notes",  placeholder: "Special preferences for this customer, e.g. small potatoes only",  input_html: { class: "input-block-level" }

app/views/distributor/customers/_index.html.haml
-# XXX: `cache_if` so we don't cache search and tag sub-routes
- cache_if(request.fullpath == distributor_customers_path, [request.fullpath, current_distributor.id, Date.current.iso8601, customers.map(&:id).hash, customers.maximum(:updated_at)]) do
  %table#customers.table.table-striped
    %thead
      %tr
        %th{ colspan: 3 }
          %span#transactional_customer_count{title: "Total customers: #{current_distributor.customers.count}<br />Transactional customers: #{current_distributor.transactional_customer_count}"}
            %i.icon-user
            = pluralize(customers.count, "customer")
        %th{ colspan: 3 }
          Next Delivery
        %th
          Total:
          = customers_total_balance

    %tbody
      %tr.new-row
        %td{ colspan: 7 }= link_to 'Create a new customer', new_distributor_customer_path

        - customers.each do |customer|
          %tr.customer-row
            %td= check_box_tag customer.id, 1, false, class: "select_one", 'data-customer-id' => customer.id
            %td= customer_badge(customer)
            %td
              = customer_tags(customer)
            %td
              %small= next_customer_delivery_occurrence(customer)
            %td
              %small= next_customer_delivery_box_name(customer)
            %td
              %small= customer.account.delivery_service.name
            %td
              %span.balance{ class: "#{'negative' if customer.account.balance.negative?}" }= customer.account.balance

app/views/distributor/customers/edit_delivery_details.html.haml
- title("Update Delivery Details", false)
= content_tag(:h1, "Update Delivery Details for #{customer_badge(delivery_details.customer)}".html_safe, class: 'text-center')

= simple_form_for(delivery_details, url: update_delivery_details_distributor_customer_path(delivery_details.customer), html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  = render partial: "edit_delivery_details_inputs", locals: { f: f, delivery_details: delivery_details }

  .row-fluid
    .span12.form-actions
      = f.button :submit, 'Update', class: 'btn btn-primary'
      or
      = link_to 'cancel', :back

app/views/distributor/customers/edit_profile.html.haml
- title("Update Profile", false)
= content_tag(:h1, "Update Profile for #{customer_badge(customer_profile.customer)}".html_safe, class: 'text-center')

= simple_form_for(customer_profile, url: update_profile_distributor_customer_path(customer_profile.customer), html: { class: "form-horizontal" }) do |f|
  = f.error_notification

  = render partial: "edit_profile_inputs", locals: { f: f, customer_profile: customer_profile }

  .row-fluid
    .span12.form-actions
      = f.button :submit, "Update", class: "btn btn-primary"
      or
      = link_to "cancel", :back

app/views/distributor/customers/index.html.haml
- title 'Customers', false
= render 'controls'
= intro_tour(@show_tour)

= render partial: 'index', locals: { customers: @customers, customers_total_balance: @customers_total_balance }

app/views/distributor/customers/new.html.haml
- title('New Customer')

= simple_form_for(new_customer, url: distributor_customers_path, html: { class: 'form-horizontal', method: :post }) do |f|
  = f.error_notification

  = render partial: "edit_profile_inputs", locals: { f: f, customer_profile: new_customer }
  = render partial: "edit_delivery_details_inputs", locals: { f: f, delivery_details: new_customer }

  .row-fluid
    .span12.form-actions
      = f.button :submit, 'Create Customer', class: 'btn btn-primary'
      or
      = link_to 'cancel', :back

app/views/distributor/customers/show.html.haml
= render 'controls'
= intro_tour(@show_tour)

.row-fluid
  #customer-details.span4
    #section-one
      = customer_title(@customer, class: 'important')
      = customer_tags(@customer)

      #account-information{data: {account_id: @account.id}}
        %span.balance{ class: "#{'negative' if @account.negative_balance?}" }= @account.balance

      %ul.unstyled
        - unless @customer.discount.zero?
          %li
            Discount:
            %strong= number_to_percentage(@customer.discount*100.0, {precision: 1})
        - if @customer.halted? || @customer.balance_threshold_cents != @customer.default_balance_threshold_cents
          %li
            %span.highlightable{class: @customer.halted? ? 'highlighted' : ''}
              Minimum balance:
              %strong= @customer.balance_threshold
        %li
          Email:
          %strong= @customer.email
        - unless @address.mobile_phone.blank?
          %li
            Mobile:
            %strong= @address.mobile_phone
        - unless @address.home_phone.blank?
          %li
            Home:
            %strong= @address.home_phone
        - unless @address.work_phone.blank?
          %li
            Work:
            %strong= @address.work_phone

      - unless @customer.special_order_preference.blank?
        %p.note-field= @customer.special_order_preference

      %small= link_to 'edit profile', edit_profile_distributor_customer_path(@customer)
      - if @orders.none? { |order| order.has_yellow_deliveries? }
        \|
        %small= link_to 'delete customer', distributor_customer_path, method: :delete, confirm: 'Are you sure? This cannot be undone.'

      %br

      %small= link_to 'send logins', send_login_details_distributor_customer_path(@customer), confirm: 'Are you sure? This will reset their password.'
      \|
      %small= link_to 'impersonate', impersonate_distributor_customer_path(@customer), target: '_blank'

    #section-two
      %span.heading.red= @customer.delivery_service.name
      - if @address
        %address= @address.join('<br>')

      - unless @address.delivery_note.blank?
        %p.note-field= @address.delivery_note

      %small= link_to 'edit delivery details', edit_delivery_details_distributor_customer_path(@customer)

  #customer-associations.span8
    .row-fluid
      #note-section.span12
        %fieldset
          %legend notes
          = simple_form_for([:distributor, @customer]) do |f|
            = f.input :notes, placeholder: 'E.g. Credit card bounced 23 July, to follow up', label: false, input_html: { class: 'span12', rows: nil }
            = f.button :submit, 'Update', class: 'btn btn-primary pull-right'

    .row-fluid
      #order-section.span12
        %fieldset
          %legend orders
          = render 'distributor/orders/index'

    .row-fluid
      #transaction-section.span12
        %fieldset
          %legend transactions
          #sortable_transactions{data: {user: 'distributor'}}
            = render 'distributor/transactions/index'

    .row-fluid
      #activity-section.span12{ class: "#{'hide' if @customer.recent_activities.empty?}" }
        %fieldset
          %legend recent activity
          #activities
            = render partial: 'activity', locals: { activities: @customer.recent_activities }