config/routes.rb
API_SUBDOMAIN = { subdomain: /\A(staging-)?api\Z/ }.freeze unless defined? API_SUBDOMAIN

BuckyBox::Application.routes.draw do
  apipie

  devise_for :admins,       controllers: { sessions: "admin/sessions" }
  devise_for :distributors, controllers: { sessions: "distributor/sessions", passwords: "distributor/passwords" }
  devise_for :customers,    controllers: { sessions: "customer/sessions", passwords: "customer/passwords" }

  get "/ping" => "application#ping"
  get "/delayed_job" => DelayedJobWeb, anchor: false
  get "/" => "api#index", constraints: API_SUBDOMAIN

  root to: "distributor/customers#index"

  namespace :sign_up_wizard do
    get "form"
    get "country"
    post "sign_up"
  end

  namespace :distributor do
    root to: "welcome#index"

    namespace :settings do
      get "organisation"
      get "webstore"
      post "webstore", action: "save_webstore"
      post "spend_limit_confirmation"

      resource :delivery_services, only: [:show, :create, :update, :destroy]

      namespace :products do
        resource :boxes, only: [:show, :create, :update]
        resource :box_items, only: [:show, :create, :update]
        resource :extra_items, only: [:show, :create, :update]
      end

      namespace :payments do
        resource :bank_deposit, controller: "bank_deposit", only: [:show, :update]
        resource :cash_on_delivery, controller: "cash_on_delivery", only: [:show, :update]
        resource :paypal, controller: "paypal", only: [:show, :update]
      end
    end

    namespace :notifications do
      post "dismiss_all", actions: "dismiss_all", as: "dismiss_all"
    end

    namespace :intro_tour do
      post "dismiss", actions: "dismiss", as: "dismiss"
    end

    namespace :reports do
      get "/",                               action: "index"
      get "transaction_history/:start/:to",  action: "transaction_history",      as: "transaction_history"
      get "customer_account_history/:to",    action: :customer_account_history,  as: "customer_account_history"
    end

    resource :billing, only: :show, controller: "billing"
    resource :pricing, only: :update, controller: "pricing"

    resources :distributors,        only: :update
    resource  :bank_information,    only: :update
    resources :boxes,               except: [:index]
    resources :extras,              except: [:index, :show]

    resources :line_items, except: [:index, :show, :update] do
      collection do
        put "bulk_update", action: :bulk_update, as: "bulk_update"
      end
    end

    resources :deliveries

    resources :payments, only: [:index, :destroy] do
      collection do
        post "match_payments", action: "match_payments", as: "match_payments"
      end

      member do
        put "process_payments", action: "process_payments", as: "process_payments"
      end
    end

    resources :import_transactions, only: [:update] do
      member do
        get "load_more_rows/:position", action: "load_more_rows", as: "load_more_rows"
      end
    end

    resources :import_transaction_lists, only: [:destroy]

    resources :customers, except: [:edit] do
      collection do
        get "search",   action: :index, as: "search"
        get "tag/:tag", action: :index, as: "tag"
        post "email"
        post "export"
      end

      member do
        get :send_login_details
        get "impersonate"
        get "activity"
        get "edit_profile",             action: "edit_profile",             as: "edit_profile"
        put "update_profile",           action: "update_profile",           as: "update_profile"
        get "edit_delivery_details",    action: "edit_delivery_details",    as: "edit_delivery_details"
        put "update_delivery_details",  action: "update_delivery_details",  as: "update_delivery_details"
      end
    end

    resources :accounts, only: :edit do
      resources :orders, except: [:index, :show, :destroy] do
        member do
          put "deactivate"
          put "pause"
          post "remove_pause"
          put "resume"
          post "remove_resume"
        end
      end

      resources :boxes do
        member do
          get "extras"
        end
      end

      member do
        put "change_balance", action: :change_balance, as: "change_balance"
        get "transactions/:limit(/:more)", action: :transactions, as: "transactions"
        get "receive_payment", action: :receive_payment, as: "receive_payment"
        post "save_payment",   action: :save_payment, as: "save_payment"
      end
    end
  end

  namespace :customer do
    root to: "dashboard#index"

    get "dashboard",               controller: "dashboard", action: "index"
    get "order/:order_id/box/:id", controller: "dashboard", action: "box"

    put "update_contact_details",   controller: "customers",  action: "update_contact_details"
    put "update_delivery_address",  controller: "customers",  action: "update_delivery_address"
    put "update_password",          controller: "customers",  action: "update_password"

    resources :boxes, only: [:show] do
      member do
        get "extras"
      end
    end

    resources :orders, only: [:edit, :update] do
      member do
        put "pause"
        post "remove_pause"
        put "resume"
        post "remove_resume"
        put "deactivate"
      end
    end

    resources :accounts, only: [] do
      get "transactions/:limit(/:more)", action: :transactions, as: "transactions"
    end
  end

  namespace :admin do
    root to: "dashboard#index"

    resources :cron_logs, only: :index
    resources :style_sheet, only: :index

    resources :metrics, only: [:index] do
      collection do
        get "transactional_customers"
        get "sales"
      end
    end

    resources :distributors, only: [:index, :new, :create, :edit, :update] do
      member do
        get "impersonate"
      end

      collection do
        get "unimpersonate"
        get "country_setting/:id", controller: "distributors", action: "country_setting"
        get "tag/:tag", action: :index, as: "tag"
      end
    end

    resources :omni_importers do
      member do
        post "test"
      end
    end
  end

  namespace :api, path: "", defaults: { format: :json }, constraints: API_SUBDOMAIN do
    namespace :v1 do
      get  "ping"                => "base#ping"
      post "csp-report"          => "base#csp_report"
      get  "geoip(/:ip)"         => "base#geoip", constraints: { ip: %r{[^\/]+} } # accept IP including dots

      post "/customers/sign_in"
      resources :customers,         only: [:index, :show, :create, :update]
      resources :boxes,             only: [:index, :show]
      resources :delivery_services, only: [:index, :show]
      resources :orders,            only: [:index, :show, :create]
      resources :webstores,         only: [:index] # all webstores
      resource  :webstore,          only: [:show] # current webstore
      resources :deliveries,        only: [:index] do
        get :pending, on: :collection
      end
    end
  end

  # TODO: Legacy routes. As we move to all RESTful routes these should be removed.
  get "/distributor/deliveries/date/:date/view/:view",            controller: "distributor/deliveries", action: :index,                           as: "date_distributor_deliveries"
  post "/distributor/deliveries/date/:date/reposition",           controller: "distributor/deliveries", action: :reposition,                      as: "reposition_distributor_deliveries"
  post "/distributor/deliveries/update_status",                   controller: "distributor/deliveries", action: :update_status,                   as: "update_status_distributor_deliveries"
  post "/distributor/deliveries/make_payment",                    controller: "distributor/deliveries", action: :make_payment,                    as: "make_payment_distributor_deliveries"
  post "/distributor/deliveries/master_packing_sheet",            controller: "distributor/deliveries", action: :master_packing_sheet,            as: "master_packing_sheet_distributor_deliveries"

  post "/distributor/deliveries/export",                          controller: "distributor/export/deliveries",               action: :index, as: "export_distributor_deliveries"
  post "/distributor/deliveries/export_extras",                   controller: "distributor/export/extras",                   action: :index, as: "export_extras_distributor_deliveries"
  post "/distributor/deliveries/export_exclusions_substitutions", controller: "distributor/export/exclusions_substitutions", action: :index, as: "export_exclusions_substitutions_distributor_deliveries"
end

app/controllers/admin/style_sheet_controller.rb
class Admin::StyleSheetController < Admin::BaseController
end

app/views/admin/style_sheet/index.html.haml
= link_to "Back to Admin", admin_root_path

%h1 Bucky Box Style Sheet

%blockquote #{link_to "Live Style Sheet", "https://www.dropbox.com/s/cacfw3oj1dy9pgp/xxx-master-styling-guide.fw.png"} by Will

%ul
  %li Use these shared styles and #{link_to "Bootstrap", "http://twitter.github.io/bootstrap/"} styles when possible, fallback to custom CSS only if necessary.

  %li
    Unless stated otherwise, all text in HTML markup should be lowercase and
    = link_to "text-transform", "https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform"
    will enforce consistency for each class.

%ul
  %li.grey Grey #EFEFEF
  %li.yellow Yellow #FAE1A0
  %li.red Red #F9D9D9
  %li.green Green #D4E4C4

%table.table.table-hover.table-bordered
  %thead
    %tr
      %th Class
      %th Usage
      %th Example
      %th{width: "40%"} Notes
  %tbody
    %tr
      %td (none)
      %td Regular link
      %td
        %a cancel
      %td
        %ul
          %li Different style on hover
    %tr
      %td .action
      %td Action link
      %td
        %a.action Create a new customer
      %td
        %ul
          %li Color used for actions
          %li Different style on hover
          %li First letter must be capitalised in markup (#{link_to "text-transform", "https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform"} can't do it)
    %tr
      %td .secondary-action
      %td Secondary action link
      %td
        %a.secondary-action cancel
      %td
        %ul
          %li Different style on hover
    %tr
      %td .minor-action
      %td Minor action link
      %td
        %a.minor-action pause
      %td
        %ul
          %li Different style on hover
    %tr
      %td fieldset > legend, .modal-header > span:not(.raw), .heading
      %td
        Heading
      %td
        %span.heading heading
        %span.heading.red delivery service
      %td
        %ul
          %li
            %code .raw
            can be used for raw (unstyled) modal titles such as the emailer
    %tr
      %td .label
      %td
        Tag
      %td
        .label.label-info credit card
      %td
        %ul
          %li= link_to "Other types (colors) available", "http://twitter.github.io/bootstrap/components.html#labels-badges"
    %tr
      %td .label.label-warning
      %td
        Warning labels
      %td
        .label.label-warning This will affect 8 customers
      %td
        %ul
    %tr
      %td fieldset > legend
      %td
        Form section
      %td
        %fieldset
          %legend Legend
          %em form fields
      %td
    %tr
      %td .customer-badge
      %td Customer badge
      %td
        = customer_badge(Customer.last)
      %td
        %ul
          %li Includes HTML5 data attributes for JavaScript use:
          %ul
            %li <code>data-customer-id</code>
            %li <code>data-customer-email</code>
    %tr
      %td .badge
      %td ???
      %td
        %span.badge badge
      %td
        %ul
          %li.bold Where would we use it?
          %li= link_to "Other types (colors) available", "http://twitter.github.io/bootstrap/components.html#labels-badges"
    %tr
      %td "data-toggle" => "tooltip"
      %td Extra information
      %td
        %a{"href" => "javascript:void()", "data-toggle" => "tooltip", "data-original-title" => "Title"} Hover me
        :javascript
          $('[data-toggle="tooltip"]').tooltip();
      %td
        %ul
          %li= link_to "More information", "http://twitter.github.io/bootstrap/javascript.html#tooltips"
    %tr
      %td "data-toggle" => "popover"
      %td Extra long information
      %td
        %a{"href" => "javascript:void()", "data-toggle" => "popover", "data-original-title" => "My title", "data-content" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce ac mauris nunc. Maecenas massa urna, hendrerit eu pretium eu, faucibus in massa. Aliquam tincidunt est eget mauris tincidunt sodales. Fusce sollicitudin euismod tortor sit amet consequat. Aenean volutpat dui sit amet neque imperdiet aliquet."} Click me
        :javascript
          $('[data-toggle="popover"]').popover();
      %td
        %ul
          %li= link_to "More information", "http://twitter.github.io/bootstrap/javascript.html#popovers"
    %tr
      %td .alert.alert-error
      %td Error message
      %td
        .alert.alert-error
          = link_to "javascript:void()", class: "close", "data-dismiss" => "alert" do
            %i.icon-remove
          Oops!
      %td
        %ul
          %li Close button is optional
          %li= link_to "More information", "http://twitter.github.io/bootstrap/components.html#alerts"
    %tr
      %td .alert.alert-success
      %td Success message
      %td
        .alert.alert-success
          = link_to "javascript:void()", class: "close", "data-dismiss" => "alert" do
            %i.icon-remove
          All good!
      %td
        %ul
          %li Close button is optional
          %li= link_to "More information", "http://twitter.github.io/bootstrap/components.html#alerts"
    %tr
      %td .alert.alert-info
      %td Informational message
      %td
        .alert.alert-info
          = link_to "javascript:void()", class: "close", "data-dismiss" => "alert" do
            %i.icon-remove
          Heads up!
      %td
        %ul
          %li Close button is optional
          %li= link_to "More information", "http://twitter.github.io/bootstrap/components.html#alerts"
    %tr
      %td .important
      %td Important stuff
      %td
        %span.important Watch out!
      %td
        %ul
          %li.bold Should we replace it with <code>.alert.alert-info</code>?
    %tr
      %td .amount
      %td Positive amount
      %td.text-right
        %span.amount= CrazyMoney.new(13.37).with_currency("NZD")
      %td
        %ul
          %li.bold Should we rename it to <code>.money</code> for more generic usage?
    %tr
      %td .balance
      %td Positive balance
      %td.text-right
        %span.balance= CrazyMoney.new(13.37).with_currency("NZD")
      %td
        %ul
          %li.bold Should we rename it to <code>.money</code> for more generic usage?
    %tr
      %td .balance.negative
      %td Negative balance
      %td.text-right
        %span.balance.negative= CrazyMoney.new(-13.37).with_currency("NZD")
      %td
        %ul
          %li.bold Should we rename it to <code>.money</code> for more generic usage?
    %tr
      %td .btn.btn-primary
      %td Primary button
      %td
        %a.btn.btn-primary send
      %td
        %ul
          %li Different style on hover
          %li HTML tag can be a <code>&lt;button&gt;</code> or <code>&lt;a&gt;</code> (preferred)
    %tr
      %td .btn
      %td Regular button
      %td
        %a.btn
          %i.icon-arrow-left
      %td
        %ul
          %li Different style on hover
          %li HTML tag can be a <code>&lt;button&gt;</code> or <code>&lt;a&gt;</code> (preferred)
    %tr
      %td (none)
      %td Input field
      %td
        %input
      %td
        %ul
          %li Same style for <code>&lt;textarea&gt;</code>
    %tr
      %td .required
      %td Required input field
      %td
        %input.required
      %td
        %ul
          %li Same style for <code>&lt;textarea&gt;</code>
    %tr
      %td .ajax-spinner
      %td AJAX spinner
      %td
        .ajax-spinner
      %td